import { drizzle } from "drizzle-orm/mysql2";
import mysql from "mysql2/promise";
import { projects, projectActivities, projectRisks, weeklyUpdates } from "./drizzle/schema.js";

const dbUrl = process.env.DATABASE_URL;
if (!dbUrl) {
  console.error("DATABASE_URL não configurada.");
  process.exit(1);
}

const connection = await mysql.createConnection(dbUrl);
const db = drizzle(connection);

console.log("Iniciando seed de dados demonstrativos...");

// Limpar tabelas existentes
await connection.execute("DELETE FROM weekly_updates");
await connection.execute("DELETE FROM project_risks");
await connection.execute("DELETE FROM project_activities");
await connection.execute("DELETE FROM projects");

// Inserir projetos baseados no contexto da CS Compusoftware
await db.insert(projects).values([
  {
    id: 1,
    code: "200",
    name: "Implantação ERP",
    client: "Grupo São Luiz (USL)",
    managerName: "Bruno Marin",
    managerEmail: "bruno.marin@cscompusoftware.com.br",
    sponsor: "Diretoria de Operações USL",
    status: "amarelo",
    stage: "Implantação / Homologação",
    startDate: "2025-10-01",
    plannedEndDate: "2026-03-31",
    projectedEndDate: "2026-04-18",
    baselineHours: "1840.00",
    plannedHours: "1920.00",
    actualHours: "1480.00",
    completionPct: "72.40",
    spi: "0.89",
    cpi: "0.94",
    totalModules: 11,
    totalActivities: 48,
    activeConsultants: 18,
    summary: "Projeto principal com módulos de RH, Agrícola, Automotivo, Industrial e Financeiro. Alerta para sobreposição em RH e falta de cobertura temporária no módulo Industrial.",
  },
  {
    id: 2,
    code: "204",
    name: "Atualização Tecnológica e Fiscal",
    client: "Agropecuária Vale Verde",
    managerName: "Mariana Rezende",
    managerEmail: "mariana.rezende@cscompusoftware.com.br",
    sponsor: "Gerência Financeira",
    status: "verde",
    stage: "Virada de Versão",
    startDate: "2025-11-15",
    plannedEndDate: "2026-02-28",
    projectedEndDate: "2026-02-25",
    baselineHours: "620.00",
    plannedHours: "620.00",
    actualHours: "490.00",
    completionPct: "84.00",
    spi: "1.04",
    cpi: "1.02",
    totalModules: 4,
    totalActivities: 22,
    activeConsultants: 6,
    summary: "Cronograma acelerado com entrega do módulo fiscal e contábil adiantada. Homologação final sem impedimentos graves.",
  },
  {
    id: 3,
    code: "215",
    name: "Módulo Gestão de Frota e Pecuária",
    client: "Agroindustrial Santa Rita",
    managerName: "Carlos Eduardo Neves",
    managerEmail: "carlos.neves@cscompusoftware.com.br",
    sponsor: "Diretoria Agrícola",
    status: "vermelho",
    stage: "Parametrização Crítica",
    startDate: "2025-09-01",
    plannedEndDate: "2026-01-30",
    projectedEndDate: "2026-03-15",
    baselineHours: "980.00",
    plannedHours: "1150.00",
    actualHours: "1020.00",
    completionPct: "58.00",
    spi: "0.76",
    cpi: "0.81",
    totalModules: 6,
    totalActivities: 35,
    activeConsultants: 8,
    summary: "Atraso expressivo por pendências de validação do cliente em integrações com balança e controle de abastecimento.",
  },
  {
    id: 4,
    code: "220",
    name: "Consultoria de Otimização e BI",
    client: "Sementes Progresso",
    managerName: "Fernanda Prado",
    managerEmail: "fernanda.prado@cscompusoftware.com.br",
    sponsor: "PMO Corporativo",
    status: "verde",
    stage: "Validação de Dashboards",
    startDate: "2025-12-01",
    plannedEndDate: "2026-04-30",
    projectedEndDate: "2026-04-25",
    baselineHours: "480.00",
    plannedHours: "480.00",
    actualHours: "260.00",
    completionPct: "54.00",
    spi: "1.01",
    cpi: "0.98",
    totalModules: 3,
    totalActivities: 16,
    activeConsultants: 4,
    summary: "Construção de cubos e dashboards gerenciais com alta aderência e aprovação dos usuários-chave.",
  }
]);

// Inserir atividades representativas do Projeto 200 (extraídas do SQL e da imagem)
await db.insert(projectActivities).values([
  {
    projectId: 1,
    ppsaCode: "01.01.01.01",
    description: "Cargos e Salários - Parametrização Base",
    process: "Recursos Humanos",
    subprocess: "Pessoal",
    activity: "Parametrização",
    moduleName: "RH (Pessoal)",
    plannedStart: "2025-12-01",
    plannedEnd: "2025-12-19",
    actualStart: "2025-12-01",
    actualEnd: null,
    plannedHours: "120.00",
    actualHours: "96.00",
    progressPct: "80.00",
    resource: "Ademar Gois",
    location: "Presencial",
    level: 1,
    status: "em_andamento",
  },
  {
    projectId: 1,
    ppsaCode: "01.01.02.03",
    description: "Integração Ponto Eletrônico e Folha",
    process: "Recursos Humanos",
    subprocess: "Ponto e Frequência",
    activity: "Integração de Relógio",
    moduleName: "RH (Ponto / Folha)",
    plannedStart: "2025-12-01",
    plannedEnd: "2025-12-12",
    actualStart: "2025-12-01",
    actualEnd: "2025-12-15",
    plannedHours: "80.00",
    actualHours: "88.00",
    progressPct: "95.00",
    resource: "Douglas Farchetti",
    location: "Remoto",
    level: 1,
    status: "em_andamento",
  },
  {
    projectId: 1,
    ppsaCode: "01.01.03.01",
    description: "Serviço Social e Medicina do Trabalho",
    process: "Recursos Humanos",
    subprocess: "Saúde Ocupacional",
    activity: "Mapeamento e Carga de Tabelas",
    moduleName: "RH (Serv. Social / Méd. Trab.)",
    plannedStart: "2025-12-01",
    plannedEnd: "2025-12-26",
    actualStart: "2025-12-03",
    actualEnd: null,
    plannedHours: "140.00",
    actualHours: "110.00",
    progressPct: "70.00",
    resource: "Fabiano Gomes",
    location: "Presencial",
    level: 1,
    status: "em_andamento",
  },
  {
    projectId: 1,
    ppsaCode: "02.01.01.02",
    description: "GED e Fluxo de Documentos Digitais",
    process: "Geral",
    subprocess: "Documentos",
    activity: "Configuração de Perfis",
    moduleName: "Geral (GED)",
    plannedStart: "2025-12-01",
    plannedEnd: "2025-12-19",
    actualStart: "2025-12-01",
    actualEnd: null,
    plannedHours: "75.00",
    actualHours: "60.00",
    progressPct: "85.00",
    resource: "Paulo Maluizi",
    location: "Presencial",
    level: 1,
    status: "em_andamento",
  },
  {
    projectId: 1,
    ppsaCode: "03.01.02.01",
    description: "PFC, Pagamento a Fornecedores e Balança",
    process: "Agrícola",
    subprocess: "Fornecedores e Balança",
    activity: "Testes de Pesagem e Entrada",
    moduleName: "Agrícola",
    plannedStart: "2025-12-01",
    plannedEnd: "2025-12-26",
    actualStart: "2025-12-01",
    actualEnd: null,
    plannedHours: "160.00",
    actualHours: "135.00",
    progressPct: "78.00",
    resource: "Allan Silva",
    location: "Presencial",
    level: 1,
    status: "em_andamento",
  },
  {
    projectId: 1,
    ppsaCode: "04.01.01.04",
    description: "Controle de Manutenção de Frota",
    process: "Automotivo",
    subprocess: "Oficina e Manutenção",
    activity: "Parametrização Ordem de Serviço",
    moduleName: "Automotivo",
    plannedStart: "2025-12-01",
    plannedEnd: "2025-12-19",
    actualStart: "2025-12-02",
    actualEnd: null,
    plannedHours: "110.00",
    actualHours: "92.00",
    progressPct: "75.00",
    resource: "João Zampierim",
    location: "Presencial",
    level: 1,
    status: "em_andamento",
  },
  {
    projectId: 1,
    ppsaCode: "05.01.02.01",
    description: "Planejamento e Controle de Produção (PCP)",
    process: "Industrial",
    subprocess: "Produção",
    activity: "Apontamento Industrial e O.P.",
    moduleName: "Industrial",
    plannedStart: "2025-12-08",
    plannedEnd: "2026-01-09",
    actualStart: null,
    actualEnd: null,
    plannedHours: "150.00",
    actualHours: "18.00",
    progressPct: "20.00",
    resource: "Carlos Ferreira",
    location: "Remoto",
    level: 1,
    status: "atrasado",
  },
  {
    projectId: 1,
    ppsaCode: "06.01.01.01",
    description: "Contas a Pagar e Contas a Receber",
    process: "Financeiro",
    subprocess: "Tesouraria",
    activity: "Conciliação e Fechamento",
    moduleName: "Financeiro",
    plannedStart: "2025-12-01",
    plannedEnd: "2025-12-26",
    actualStart: "2025-12-01",
    actualEnd: null,
    plannedHours: "140.00",
    actualHours: "105.00",
    progressPct: "82.00",
    resource: "Jaqueline Fujisawa",
    location: "Presencial",
    level: 1,
    status: "em_andamento",
  }
]);

// Inserir Riscos e Problemas para o Projeto 200
await db.insert(projectRisks).values([
  {
    projectId: 1,
    title: "Sobreposição de alocação de consultor especialista",
    category: "Recurso",
    severity: "critico",
    probability: "alto",
    impact: "Fabiano Gomes alocado simultaneamente no RH (Ponto) e RH (Serviço Social / Medicina) na mesma semana.",
    mitigationPlan: "Deslocar alocação de ponto para Douglas Farchetti e manter Fabiano focado em Saúde Ocupacional.",
    owner: "Bruno Marin",
    dueDate: "2025-12-18",
    status: "em_mitigacao",
  },
  {
    projectId: 1,
    title: "Módulo Industrial sem cobertura planejada na semana 5",
    category: "Cronograma",
    severity: "alto",
    probability: "alto",
    impact: "Período 29/12 a 02/01 com parada técnica na fábrica sem consultor presencial agendado.",
    mitigationPlan: "Antecipar testes de apontamento industrial com Carlos Ferreira e agendar plantão remoto.",
    owner: "Carlos Ferreira",
    dueDate: "2025-12-22",
    status: "aberto",
  },
  {
    projectId: 1,
    title: "Atraso na validação das regras de negócio do Cliente",
    category: "Cliente",
    severity: "medio",
    probability: "medio",
    impact: "Demora na assinatura do aceite de parametrização de compras agrícolas e balança.",
    mitigationPlan: "Alinhamento com o Sponsor do Grupo São Luiz na reunião de quinta-feira.",
    owner: "Bruno Marin",
    dueDate: "2025-12-20",
    status: "aberto",
  },
  {
    projectId: 3,
    title: "Falta de infraestrutura de rede na unidade remota de balança",
    category: "Técnico",
    severity: "critico",
    probability: "alto",
    impact: "Balança rodoviária sem comunicação com o servidor central, bloqueando testes finais.",
    mitigationPlan: "Equipe de TI do cliente implantará enlace redundante até o fim da semana.",
    owner: "Carlos Eduardo Neves",
    dueDate: "2025-12-19",
    status: "aberto",
  }
]);

// Inserir histórico de atualizações semanais
await db.insert(weeklyUpdates).values([
  {
    projectId: 1,
    weekReference: "Semana 49 / 2025",
    authorName: "Bruno Marin",
    authorRole: "Gerente de Projetos",
    ragStatus: "verde",
    physicalProgressPct: "67.50",
    spiValue: "0.95",
    cpiValue: "0.97",
    hoursConsumedWeek: "164.00",
    whatOccurred: "Concluída a homologação da folha de pagamento e validados os parâmetros contábeis iniciais.",
    nextSteps: "Iniciar os testes de integração com os módulos de oficina mecânica e pesagem agrícola.",
    criticalAttention: "Manter agenda dos usuários-chave confirmada com 48h de antecedência.",
    clientDecisionsNeeded: "Definição do modelo de rateio de frete entre filiais.",
  },
  {
    projectId: 1,
    weekReference: "Semana 50 / 2025",
    authorName: "Bruno Marin",
    authorRole: "Gerente de Projetos",
    ragStatus: "amarelo",
    physicalProgressPct: "72.40",
    spiValue: "0.89",
    cpiValue: "0.94",
    hoursConsumedWeek: "182.00",
    whatOccurred: "Avanço nos módulos de RH e Agrícola, porém com gargalo no módulo Industrial e sobreposição de consultores.",
    nextSteps: "Readequar alocação de Fabiano Gomes e fechar plantão do módulo Industrial para a virada de ano.",
    criticalAttention: "Risco de atraso no go-live da fábrica se a homologação de PCP não for iniciada até 22/12.",
    clientDecisionsNeeded: "Aprovação do calendário de parada da fábrica para carga dos dados de estoque.",
  }
]);

console.log("Seed finalizado com sucesso!");
await connection.end();
